#! /bin/bash





acao=$(dialog --stdout\
      --menu "aplicativo"\
      0 0 0\
      1 "criar pendrive com versao mais recente do debian" \
      2 "criar pendrive com versao mais recente do ubuntu")
clear


case "$acao" in 
1)
  URL='https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.7.0-amd64-netinst.iso';;
2)
  URL='https://ubuntu.com/download/desktop/thank-you?version=24.04.1&architecture=amd64&lts=true';;
esac
  wget --progress=dot "$URL" -O /tmp/arq.iso 2>&1|\
  grep "%" |\
  sed -u -e "s,\.,,g" | awk '{print $2}' | sed -u -e "s,\%,,g" | dialog --gauge "Download Test" 10 100
clear

dispositivo=$(dialog --stdout --inputbox "digite o caminho do pendrive" 0 0)


#$(umount $dispositivo)
#$(mkfs.exfat -I $dispositivo)

#$(apt-get install pv)
#$(dd if=/tmp/arq.iso |pv| dd of=$dispositivo | dialog --gauge "download" 10 100)
clear


#echo $dispositivo
