#!/bin/bash

if [ $UID -ne 0 ]; then
    # Se for diferente de 0, imprime mensagem de erro.
    echo "Requer privilégio de root."

    # Finaliza o script
    exit 1
fi

apt-get install build-essentials binutils
apt install -y g++ make cmake wget unzip libopencv-dev libgtk-3-dev libpng++-dev libpng16-16 libpng-dev

wget -O opencv.zip https://github.com/opencv/archive/master.zip
unzip opencv.zip
mv opencv-master opencv_lib
mkdir -p build && cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE CMAKE_INSTALL_PREFIX=/usr/local WITH_CUDA=ON ENABLE_FAST_MATH=1 CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 BUILD_EXEMPLES=ON
make
make install
